### ISSUE TITLE
"tabs" permission

### ISSUE THREAD

**Issue by keysmashes** [tarla/random-wikipedia-chrome-extension#1]
Does this extension actually need the `tabs` permission?

The [docs](https://developer.chrome.com/extensions/tabs) say that you only need to request the permission if you access the `url`, `title` or `favIconUrl` properties of a tab, and it seems unlikely that the permission is required to construct a tab with a given URL.

The Chrome Web Store warns users that extensions with the `tabs` permission can "Read your browsing history", so it would be optimal if the permission could be removed.

**Comment by tarla** [comment]
@sersorrel it may be a bit late, but I'm removing this unnecessary permission now. thank you 🙏
